pipeline {
  agent any 
  
  stages {

    stage("paso 1"){
        
        stage('Build') {
                steps {
                    echo 'Building..'
                }
        }
        stage('Test') {
                steps {
                    echo 'Testing..'
                }
        }
        stage('Deploy') {
                steps {
                    echo 'Deploying....'
                }
        }
      }
      post {
        always {          
              sh "echo 'fase always'"
        }
        success {
              sh "echo 'fase success'"
        }
        failure {
              sh "echo 'fase failure'"
        }

  }
}  

